services:
  nginx:
    container_name: reverse-proxy
    image: nginx:1.29-alpine
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - ${NGINX_PORT:-80}:80
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - front
      - api

  front:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env.dev
    ports:
      - ${FRONTEND_PORT:-4000}:80
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    restart: always
    ports:
      - ${API_PORT:-5000}:80
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - database
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq-mensageria
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672/" ]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    container_name: postgres
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
    ports:
      - ${DB_PORT:-5432}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3
