FROM node:25 AS dev

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

RUN npx prisma generate

EXPOSE 80

CMD [ "npm", "run", "start:dev" ]
